import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin:
https://github.com/JuanFerber/obsidian-pdf-studio
*/
`;

const prod =
  process.env.BUILD_ENV === "production" || process.argv.includes("production");

// Build output directory
const BUILD_DIR = "build";

// Resolve local vault directory dynamically from .local/vault-path.txt or environment variable
function getVaultPluginDir() {
  if (process.env.OBSIDIAN_vaultDir) {
    return process.env.OBSIDIAN_vaultDir.trim();
  }
  const localConfigPath = path.resolve(".local/vault-path.txt");
  if (fs.existsSync(localConfigPath)) {
    const target = fs.readFileSync(localConfigPath, "utf8").trim();
    if (target.length > 0) {
      return target;
    }
  }
  return null;
}

// Ensures build directory exists and copies static assets (manifest, styles) into it
function prepareBuildDir() {
  if (!fs.existsSync(BUILD_DIR)) {
    fs.mkdirSync(BUILD_DIR, { recursive: true });
  }
  const staticFiles = ["manifest.json", "styles.css"];
  for (const file of staticFiles) {
    if (fs.existsSync(file)) {
      fs.copyFileSync(file, path.join(BUILD_DIR, file));
    }
  }
}

// Synchronizes the build/ directory contents directly to the local test vault
function copyToVault() {
  const vaultDir = getVaultPluginDir();
  if (!vaultDir) return;

  try {
    if (!fs.existsSync(vaultDir)) {
      fs.mkdirSync(vaultDir, { recursive: true });
    }
    const filesToCopy = ["main.js", "manifest.json", "styles.css"];
    for (const file of filesToCopy) {
      const srcPath = path.join(BUILD_DIR, file);
      if (fs.existsSync(srcPath)) {
        fs.copyFileSync(srcPath, path.join(vaultDir, file));
      }
    }
    console.log(
      `[Sync] Files successfully synchronized from ${BUILD_DIR}/ to vault: ${vaultDir}`,
    );
  } catch (err) {
    console.error("[Sync] Failed to sync files to vault:", err);
  }
}

// Esbuild plugin to assemble the build/ directory and sync upon compilation
const syncPlugin = {
  name: "sync-to-vault-plugin",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length === 0) {
        prepareBuildDir();
        copyToVault();
      }
    });
  },
};

// Initial directory check
prepareBuildDir();

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(BUILD_DIR, "main.js"),
  minify: prod,
  plugins: [syncPlugin],
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  console.log("[Build] Production build completed successfully.");
} else {
  await context.watch();
  console.log(
    "[Watch] Development mode active. Watching for changes in src/...",
  );
}
