import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import builtins from "builtin-modules";

const banner = `/*
    THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
    If you want to view the source, please visit the github repository of this plugin:
    https://github.com/JuanFerber/obsidian-pdf-studio
    */
    `;

const prod =
  process.env.BUILD_ENV === "production" || process.argv.includes("production");

// Resolve local vault directory dynamically from .local/vault-path.txt or environment variable
function getVaultPluginDir() {
  if (process.env.OBSIDIAN_vaultDir) {
    return process.env.OBSIDIAN_vaultDir.trim();
  }
  const localConfigPath = path.resolve(".local/vault-path.txt");
  if (fs.existsSync(localConfigPath)) {
    const target = fs.readFileSync(localConfigPath, "utf8").trim();
    if (target.length > 0) {
      return target;
    }
  }
  return null;
}

function copyToVault() {
  const vaultDir = getVaultPluginDir();

  if (!vaultDir) return;

  try {
    if (!fs.existsSync(vaultDir)) {
      fs.mkdirSync(vaultDir, { recursive: true });
    }
    const filesToCopy = ["main.js", "manifest.json", "styles.css"];
    for (const file of filesToCopy) {
      if (fs.existsSync(file)) {
        fs.copyFileSync(file, path.join(vaultDir, file));
      }
    }
    console.log(`[Sync] Files synchronized to vault: ${vaultDir}`);
  } catch (err) {
    console.error("[Sync] Failed to sync files to vault:", err);
  }
}

// Esbuild plugin to automatically sync built files upon successful compilation
const syncPlugin = {
  name: "sync-to-vault-plugin",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length === 0) {
        copyToVault();
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [syncPlugin],
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  console.log("[Build] Production build completed successfully.");
} else {
  await context.watch();
  console.log(
    "[Watch] Development mode active. Watching for changes in src/...",
  );
}
